# Generated by Django 4.2.7 on 2026-06-09 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SymptomCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_symptoms", models.TextField(db_column="symptoms", default="[]")),
                ("severity", models.IntegerField()),
                ("duration_days", models.IntegerField()),
                ("age_at_check", models.IntegerField()),
                ("notes", models.TextField(blank=True, default="")),
                ("predicted_disease", models.CharField(blank=True, max_length=200)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "_all_predictions",
                    models.TextField(db_column="all_predictions", default="[]"),
                ),
                (
                    "_recommended_tablets",
                    models.TextField(db_column="recommended_tablets", default="[]"),
                ),
                (
                    "_home_remedies",
                    models.TextField(db_column="home_remedies", default="[]"),
                ),
                ("doctor_recommendation", models.TextField(blank=True)),
                (
                    "severity_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mild", "Mild"),
                            ("Moderate", "Moderate"),
                            ("Severe", "Severe"),
                            ("Critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("emergency_flag", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
